name: Deploy Symposium

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      
      - name: Install Dependencies
        run: composer install --no-dev --optimize-autoloader
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      
      - name: Install NPM Dependencies and Build
        run: |
          npm ci
          npm run build
      
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          echo "Host nardos.info" > ~/.ssh/config
          echo "  IdentityFile ~/.ssh/deploy_key" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
      
      - name: Deploy to Production
        run: |
          ssh ${{ secrets.SSH_USERNAME }}@nardos.info '
            cd /var/www/symposium &&
            git pull origin main &&
            composer install --no-dev --optimize-autoloader &&
            touch database/database.sqlite &&
            chmod 775 database/database.sqlite &&
            php artisan migrate --force &&
            php artisan config:cache &&
            php artisan route:cache &&
            php artisan view:cache &&
            npm ci &&
            npm run build &&
            sudo chown -R www-data:www-data . &&
            sudo systemctl reload nginx
          '
